collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
