defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "*.config.js"
  - "package*.json"
  - "_tailwind"
  - "node_modules"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
